#!/usr/bin/env node

if (!require('assert').strict) {
	console.error("We require Node.js version 10 or later; you're using " + process.version);
	process.exit(1);
}

if (parseInt(process.version.slice(1)) < 20) {
	var nvmDirs = [
		require('path').join(__dirname, '.node'),
		require('path').join(process.env.HOME || '/root', '.nvm/versions/node'),
		'/home/gyarados/.nvm/versions/node',
	];
	var newerNode = '';
	for (var d = 0; d < nvmDirs.length && !newerNode; d++) {
		try {
			var versions = require('fs').readdirSync(nvmDirs[d])
				.map(function (v) { return v.replace(/^v/, '').split('.').map(Number); })
				.filter(function (v) { return v[0] >= 20; })
				.sort(function (a, b) { return (a[0] - b[0]) || (a[1] - b[1]) || (a[2] - b[2]); });
			if (versions.length) {
				var preferred = versions.filter(function (v) { return v[0] === 22; });
				var chosen = preferred.length ? preferred[preferred.length - 1] : versions[versions.length - 1];
				newerNode = nvmDirs[d] + '/v' + chosen.join('.') + '/bin/node';
			}
		} catch (e) {}
	}
	if (newerNode) {
		console.log("Node " + process.version + " can't run the client build; re-running with " + newerNode);
		var env = Object.assign({}, process.env);
		env.PATH = require('path').dirname(newerNode) + ':' + (env.PATH || '');
		var reexec = require('child_process').spawnSync(newerNode, process.argv.slice(1), {stdio: 'inherit', env: env});
		process.exit(reexec.status === null ? 1 : reexec.status);
	}
	console.error("The client build needs Node.js 20 or later (build-tools/update loads compiler.mjs, which " + process.version + " cannot require). Install Node 20+ or use nvm.");
	process.exit(1);
}

var execSync = require('child_process').execSync;
var fs = require('fs');

process.chdir(__dirname);

try {
	require.resolve('@babel/core');
} catch (e) {
	console.log('Installing dependencies...');
	execSync('npm install', {stdio: 'inherit'});
}

try {
	require.resolve('./config/config');
} catch (err) {
	if (err.code !== 'MODULE_NOT_FOUND') throw err; // should never happen

	console.log('config.js does not exist. Creating one with default settings...');
	fs.writeFileSync(
		'config/config.js',
		fs.readFileSync('config/config-example.js')
	);
}

var options = {cwd: __dirname, stdio: 'inherit'};
var full = '';

function newestMtime(dir) {
	var newest = 0;
	var entries;
	try {
		entries = fs.readdirSync(dir, {withFileTypes: true});
	} catch (e) {
		return 0;
	}
	for (var i = 0; i < entries.length; i++) {
		var p = dir + '/' + entries[i].name;
		var m = entries[i].isDirectory() ? newestMtime(p) : fs.statSync(p).mtimeMs;
		if (m > newest) newest = m;
	}
	return newest;
}

function indexesStale() {
	var out;
	try {
		out = fs.statSync('play.pokemonshowdown.com/data/teambuilder-tables.js').mtimeMs;
	} catch (e) {
		return true;
	}
	if (fs.statSync('./build-tools/build-indexes').mtimeMs > out) return true;
	return newestMtime('caches/pokemon-showdown/dist/data') > out;
}

switch (process.argv[2] || '') {
case 'full':
	execSync(`node ./build-tools/build-indexes`, options);
	execSync(`node ./build-tools/build-learnsets`, options);
	execSync(`node ./build-tools/build-minidex`, options);
	full = ' full';
	break;
case 'indexes':
	execSync(`node ./build-tools/build-indexes`, options);
	break;
case 'learnsets':
	execSync(`node ./build-tools/build-learnsets`, options);
	break;
case 'minidex':
case 'sprites':
	execSync(`node ./build-tools/build-minidex`, options);
	break;
case 'commands':
	execSync(`node ./build-tools/build-commands`, options);
	break;
case 'test-only':

	break;
case '':
	if (indexesStale()) {
		console.log('Server data or build-indexes changed since the last index build; rebuilding indexes...');
		execSync(`node ./build-tools/build-indexes`, options);
	}
	break;
default:
	console.log(`Unrecognized command ${process.argv[2]}`);
	process.exit();
	break;
}

execSync(`node ./build-tools/update` + full, options);

if (full) {
	try {
		execSync(`node ./build-tools/build-commands`, options);
	} catch (e) {
		console.error(e);
	}
}
