'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FALLBACK_HOST = 'play.pokemonshowdown.com';
const TABLES = [
	{ file: 'pokedex-mini.js', name: 'BattlePokemonSprites' },
	{ file: 'pokedex-mini-bw.js', name: 'BattlePokemonSpritesBW' },
];
const MIN_ENTRIES = 1000;
const MAX_BYTES = 4 * 1024 * 1024;
const SIZE_FIELDS = ['front', 'frontf', 'back', 'backf'];
const FIELD_ORDER = ['exists', 'num', ...SIZE_FIELDS];
const ID_REGEX = /^[a-z][a-z0-9]*$/;
const RESERVED_IDS = new Set(['constructor', 'prototype']);
const HOST_REGEX = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)*(?::[0-9]{1,5})?$/i;

function errorText(err) {
	if (!err || typeof err.message !== 'string') return String(err);
	return err.cause?.message ? `${err.message}: ${err.cause.message}` : err.message;
}

function resolveHost(root = ROOT) {
	let host;
	try {
		host = JSON.parse(fs.readFileSync(path.join(root, 'config/routes.json'), 'utf8')).resourceServer;
	} catch {}
	return typeof host === 'string' && HOST_REGEX.test(host) ? host.toLowerCase() : FALLBACK_HOST;
}

function parseMinidex(text, name) {
	if (typeof text !== 'string') throw new Error('not text');
	let pos = 0;
	const fail = what => {
		throw new Error(`${what} at line ${text.slice(0, pos).split('\n').length}`);
	};
	const match = regex => {
		regex.lastIndex = pos;
		const found = regex.exec(text);
		if (found) pos = regex.lastIndex;
		return found;
	};
	const ws = () => match(/[ \t\r\n]*/y);
	const expect = (regex, what) => {
		ws();
		const found = match(regex);
		if (!found) fail(`expected ${what}`);
		return found;
	};
	const punct = char => {
		ws();
		if (text[pos] !== char) fail(`expected '${char}'`);
		pos++;
	};
	const integer = (min, max, what) => {
		const n = Number(expect(/(?:0|-?[1-9][0-9]*)(?![0-9A-Za-z_$.])/y, `an integer ${what}`)[0]);
		if (!Number.isSafeInteger(n) || n < min || n > max) fail(`${what} out of range`);
		return n;
	};
	const size = () => {
		punct('{');
		const wh = {};
		for (let i = 0; i < 2; i++) {
			if (i) punct(',');
			const key = expect(/[wh](?=[ \t\r\n]*:)/y, "'w' or 'h'")[0];
			if (key in wh) fail(`duplicate '${key}'`);
			punct(':');
			wh[key] = integer(1, 4096, key);
		}
		punct('}');
		return { w: wh.w, h: wh.h };
	};
	const row = () => {
		punct('{');
		const fields = {};
		for (;;) {
			const key = expect(/[a-z]+/y, 'a field name')[0];
			if (!FIELD_ORDER.includes(key)) fail(`unknown field '${key}'`);
			if (key in fields) fail(`duplicate field '${key}'`);
			punct(':');
			if (key === 'num') {
				fields.num = integer(-100000, 100000, 'num');
			} else if (key === 'exists') {
				fields.exists = expect(/(?:true|false)(?![0-9A-Za-z_$])/y, 'true or false')[0] === 'true';
			} else {
				fields[key] = size();
			}
			ws();
			if (text[pos] !== ',') break;
			pos++;
		}
		punct('}');
		return fields;
	};

	match(/(?:[ \t\r\n]+|\/\*[^]*?\*\/|\/\/[^\n\r\u2028\u2029]*)*/y);
	const head = match(/exports\.([A-Za-z]+)[ \t]*=/y);
	if (!head) fail(`expected 'exports.${name} ='`);
	if (head[1] !== name) fail(`expected exports.${name}, found exports.${head[1]}`);
	punct('{');
	const table = new Map();
	for (;;) {
		ws();
		if (text[pos] === '}') break;
		const id = expect(/[a-z][a-z0-9]*/y, 'a sprite id')[0];
		if (RESERVED_IDS.has(id)) fail(`reserved id '${id}'`);
		punct(':');
		table.set(id, row());
		ws();
		if (text[pos] !== ',') break;
		pos++;
	}
	punct('}');
	punct(';');
	ws();
	if (pos !== text.length) fail('unexpected text after the table');
	return table;
}

function serializeMinidex(table, name, source) {
	const lines = [];
	for (const [id, fields] of table) {
		if (!ID_REGEX.test(id) || RESERVED_IDS.has(id)) throw new Error(`bad sprite id '${id}'`);
		const parts = [];
		for (const key of FIELD_ORDER) {
			const value = fields[key];
			if (value === undefined) continue;
			if (key === 'exists') {
				parts.push(`${key}:${value === true}`);
			} else if (key === 'num') {
				if (!Number.isSafeInteger(value)) throw new Error(`bad num for '${id}'`);
				parts.push(`${key}:${value}`);
			} else {
				if (!Number.isSafeInteger(value.w) || !Number.isSafeInteger(value.h)) throw new Error(`bad ${key} for '${id}'`);
				parts.push(`${key}:{w:${value.w},h:${value.h}}`);
			}
		}
		lines.push(`\t${id}:{${parts.join(',')}}`);
	}
	return `/*
DO NOT EDIT

THIS FILE IS AUTOGENERATED BY ./build-tools/phnn-minidex.js
FROM ${source}
*/

exports.${name} = {
${lines.join(',\n')}
};
`;
}

function validate(text, table) {
	let parsed;
	try {
		parsed = parseMinidex(text, table.name);
	} catch (err) {
		throw new Error(`${table.file}: ${errorText(err)}`);
	}
	if (parsed.size < MIN_ENTRIES) throw new Error(`${table.file} has only ${parsed.size} entries`);
	return parsed;
}

async function fetchText(url, timeoutMs = 30000) {
	if (new URL(url).protocol !== 'https:') throw new Error(`refusing non-https URL ${url}`);
	const response = await fetch(url, {
		redirect: 'error', headers: { 'accept-encoding': 'identity' }, signal: AbortSignal.timeout(timeoutMs),
	});
	if (response.status !== 200) throw new Error(`HTTP ${response.status} for ${url}`);
	if (Number(response.headers.get('content-length')) > MAX_BYTES) throw new Error(`${url} is too large`);
	const chunks = [];
	let total = 0;
	for await (const chunk of response.body) {
		total += chunk.byteLength;
		if (total > MAX_BYTES) {
			await response.body.cancel().catch(() => {});
			throw new Error(`${url} is too large`);
		}
		chunks.push(chunk);
	}
	return new TextDecoder('utf-8', { fatal: true }).decode(Buffer.concat(chunks));
}

function writeAtomic(dir, file, contents) {
	fs.mkdirSync(dir, { recursive: true });
	const tmp = path.join(dir, `.${file}.${process.pid}.tmp`);
	fs.writeFileSync(tmp, contents);
	fs.renameSync(tmp, path.join(dir, file));
}

async function refresh(options, log) {
	const root = options.root || ROOT;
	const outDir = options.outDir || path.join(root, 'play.pokemonshowdown.com/data');
	const cacheDir = options.cacheDir || path.join(root, 'caches/phnn-minidex');
	const base = `https://${resolveHost(root)}/data/`;
	const prefix = `Using upstream's animated sprite dimensions from ${base}... `;
	let outputs, counts, reason;
	try {
		const texts = await Promise.all(TABLES.map(table => (options.fetchText || fetchText)(base + table.file)));
		outputs = TABLES.map((table, i) => serializeMinidex(validate(texts[i], table), table.name, base + table.file));
		counts = outputs.map((output, i) => validate(output, TABLES[i]).size);
	} catch (err) {
		reason = errorText(err);
		outputs = null;
	}
	if (outputs) {
		TABLES.forEach((table, i) => writeAtomic(outDir, table.file, outputs[i]));
		try {
			TABLES.forEach((table, i) => writeAtomic(cacheDir, table.file, outputs[i]));
		} catch (err) {
			log(prefix + `DONE (${counts.join(' + ')} entries), but the last good copy was not saved (${errorText(err)})`);
			return { status: 'fetched', counts };
		}
		log(prefix + `DONE (${counts.join(' + ')} entries)`);
		return { status: 'fetched', counts };
	}
	const cacheName = path.relative(root, cacheDir) || cacheDir;
	let restored;
	try {
		const parsed = TABLES.map(table => validate(fs.readFileSync(path.join(cacheDir, table.file), 'utf8'), table));
		counts = parsed.map(table => table.size);
		restored = parsed.map((table, i) => serializeMinidex(table, TABLES[i].name, base + TABLES[i].file));
	} catch (err) {
		const why = err.code === 'ENOENT' ?
			`there is no last good copy in ${cacheName} yet` : `the last good copy is unusable (${errorText(err)})`;
		log(prefix + `FAILED (${reason}); ${why}, so battles show static sprites`);
		return { status: 'missing', reason };
	}
	TABLES.forEach((table, i) => writeAtomic(outDir, table.file, restored[i]));
	log(prefix + `FAILED (${reason}); restored the last good copy from ${cacheName}`);
	return { status: 'restored', reason, counts };
}

async function updateMinidex(options = {}) {
	const log = options.log || (line => console.log(line));
	try {
		return await refresh(options, log);
	} catch (err) {
		log(`Updating the animated sprite dimensions FAILED (${errorText(err)}); the build continues without them`);
		return { status: 'error', reason: errorText(err) };
	}
}

module.exports = { MIN_ENTRIES, TABLES, fetchText, parseMinidex, resolveHost, serializeMinidex, updateMinidex };

if (require.main === module) {
	const args = process.argv.slice(2);
	const options = {};
	for (let i = 0; i < args.length; i += 2) {
		if (!['--out-dir', '--cache-dir'].includes(args[i]) || !args[i + 1]) {
			console.error('Usage: node build-tools/phnn-minidex.js [--out-dir DIR] [--cache-dir DIR]');
			process.exit(2);
		}
		options[args[i] === '--out-dir' ? 'outDir' : 'cacheDir'] = path.resolve(args[i + 1]);
	}
	void updateMinidex(options);
}
