'use strict';

const assert = require('assert').strict;
const fs = require('fs');
const http = require('http');
const os = require('os');
const path = require('path');
const vm = require('vm');
const { after, describe, it } = require('node:test');

const repoRoot = path.resolve(__dirname, '..');
const scriptPath = path.join(repoRoot, 'build-tools/phnn-minidex.js');
const { MIN_ENTRIES, fetchText, parseMinidex, resolveHost, serializeMinidex, updateMinidex } = require(scriptPath);

const UPSTREAM_MAIN = `/*
DO NOT EDIT

THIS FILE IS AUTOGENERATED BY ./build-tools/build-minidex
*/

exports.BattlePokemonSprites = {
	substitute:{exists:false, front:{w:34, h:39}, back:{w:37, h:38}},
	bulbasaur:{num:1,front:{w:45,h:49},back:{w:52,h:50}},
	ivysaur:{num:2,front:{w:84,h:66},back:{w:76,h:68}},
	venusaur:{num:3,front:{w:106,h:77},back:{w:95,h:78},backf:{w:108,h:88}},
	venusaurmega:{num:3,front:{w:136,h:91},back:{w:131,h:92}},
	venusaurgmax:{num:3},
	charmander:{num:4,front:{w:48,h:57},back:{w:64,h:57}},
	rattata:{num:19,front:{w:43,h:61},frontf:{w:42,h:61},back:{w:43,h:64},backf:{w:54,h:69}},
	garchomp:{num:445,front:{w:115,h:108},frontf:{w:115,h:108},back:{w:126,h:106},backf:{w:124,h:103}},
	garchompmega:{num:445,front:{w:132,h:107},back:{w:163,h:111}},
	garchompmegaz:{num:445},
	vivillon:{num:666,front:{w:104,h:104},back:{w:101,h:112}},
	vivillonarchipelago:{num:666,front:{w:104,h:104},back:{w:101,h:112}},
	vivilloncontinental:{num:666,front:{w:104,h:104},back:{w:101,h:112}},
	vivillon:{num:666,front:{w:104,h:104},back:{w:101,h:112}},
	vivillon:{num:666,front:{w:104,h:104},back:{w:101,h:112}},
	vivillon:{num:666,front:{w:104,h:104},back:{w:101,h:112}},
	kommoototem:{num:784,front:{w:115,h:111},back:{w:131,h:121}},
	pokestarspirit:{num:-5011,front:{w:148,h:148},back:{w:148,h:148}},
	pokestarspiritprop:{num:-5011},
	pokestarblackdoor:{num:-5012,front:{w:128,h:96},back:{w:128,h:96}},
	pokestarblackdoorprop:{num:-5012},
	pokestarwhitedoor:{num:-5013,front:{w:128,h:96},back:{w:128,h:96}},
	pokestarwhitedoorprop:{num:-5013},
	pokestarblackbelt:{num:-5014,front:{w:96,h:96},back:{w:96,h:96}},
	pokestarblackbeltprop:{num:-5014},
	pokestarufopropu2:{num:-5001}
};
`;

const UPSTREAM_BW = `/*
DO NOT EDIT

THIS FILE IS AUTOGENERATED BY ./build-tools/build-minidex
*/

exports.BattlePokemonSpritesBW = {
	bulbasaur:{num:1,front:{w:37,h:38},back:{w:32,h:37}},
	ivysaur:{num:2,front:{w:58,h:51},back:{w:57,h:45}},
	venusaur:{num:3,front:{w:86,h:71},frontf:{w:86,h:71},back:{w:89,h:64},backf:{w:89,h:64}},
	venusaurmega:{num:3},
	venusaurgmax:{num:3},
	charmander:{num:4,front:{w:41,h:42},back:{w:44,h:44}},
	rattata:{num:19,front:{w:43,h:43},frontf:{w:43,h:43},back:{w:59,h:42},backf:{w:57,h:42}},
	garchomp:{num:445,front:{w:83,h:80},frontf:{w:83,h:80},back:{w:89,h:83},backf:{w:89,h:83}},
	garchompmega:{num:445,front:{w:93,h:80},back:{w:96,h:96}},
	garchompmegaz:{num:445},
	vivillon:{num:666,front:{w:67,h:74},back:{w:67,h:73}},
	vivillonarchipelago:{num:666,front:{w:67,h:74},back:{w:67,h:73}},
	vivilloncontinental:{num:666,front:{w:67,h:74},back:{w:67,h:73}},
	vivillon:{num:666,front:{w:67,h:74},back:{w:67,h:73}},
	vivillon:{num:666,front:{w:67,h:74},back:{w:67,h:73}},
	vivillon:{num:666,front:{w:67,h:74},back:{w:67,h:73}},
	kommoototem:{num:784},
	pokestarspirit:{num:-5011,front:{w:148,h:148},back:{w:148,h:148}},
	pokestarspiritprop:{num:-5011},
	pokestarblackdoor:{num:-5012,front:{w:128,h:96},back:{w:128,h:96}},
	pokestarblackdoorprop:{num:-5012},
	pokestarwhitedoor:{num:-5013,front:{w:128,h:96},back:{w:128,h:96}},
	pokestarwhitedoorprop:{num:-5013},
	pokestarblackbelt:{num:-5014,front:{w:96,h:96},back:{w:96,h:96}},
	pokestarblackbeltprop:{num:-5014},
	pokestarufopropu2:{num:-5001}
};
`;

const MAIN = { file: 'pokedex-mini.js', name: 'BattlePokemonSprites', text: UPSTREAM_MAIN };
const BW = { file: 'pokedex-mini-bw.js', name: 'BattlePokemonSpritesBW', text: UPSTREAM_BW };

function evaluate(text) {
	const exports = {};
	vm.runInNewContext(text, { exports });
	return exports;
}

function plain(value) {
	return JSON.parse(JSON.stringify(value));
}

function fullSize(text, seed = 0) {
	let rows = '';
	for (let i = 0; i < MIN_ENTRIES; i++) {
		rows += `\tfakemon${i}:{num:${i + seed},front:{w:${40 + (i % 50)},h:41},back:{w:42,h:43}},\n`;
	}
	return text.replace(/\{\n/, '{\n' + rows);
}

const tempDirs = [];
function tempRoot(resourceServer) {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), 'phnn-minidex-'));
	tempDirs.push(root);
	fs.mkdirSync(path.join(root, 'config'));
	if (resourceServer !== undefined) {
		fs.writeFileSync(path.join(root, 'config/routes.json'), JSON.stringify({ client: 'beta.hackmons.com', resourceServer }));
	}
	return root;
}
after(() => {
	for (const dir of tempDirs) fs.rmSync(dir, { recursive: true, force: true });
});

function outFile(root, file) {
	return path.join(root, 'play.pokemonshowdown.com/data', file);
}
function cacheFile(root, file) {
	return path.join(root, 'caches/phnn-minidex', file);
}

async function run(root, fetchImpl) {
	const lines = [];
	const result = await updateMinidex({ root, fetchText: fetchImpl, log: line => lines.push(line) });
	assert.equal(lines.length, 1, 'prints exactly one line');
	return { result, line: lines[0] };
}

function serve(texts) {
	const urls = [];
	const fetchImpl = url => {
		urls.push(url);
		const file = url.slice(url.lastIndexOf('/') + 1);
		return Promise.resolve(texts[file]);
	};
	return { urls, fetchImpl };
}

describe('upstream minidex parser', () => {
	for (const table of [MAIN, BW]) {
		it(`round-trips upstream's ${table.file} to the data the browser would get`, () => {
			const parsed = parseMinidex(table.text, table.name);
			const output = serializeMinidex(parsed, table.name, `https://play.pokemonshowdown.com/data/${table.file}`);
			const expected = evaluate(table.text)[table.name];
			const actual = evaluate(output)[table.name];
			assert.deepEqual(plain(actual), plain(expected));
			assert.deepEqual(Object.keys(actual), Object.keys(expected));
			assert.deepEqual([...parseMinidex(output, table.name)], [...parsed]);
			assert.equal(serializeMinidex(parseMinidex(output, table.name), table.name, 'x'), serializeMinidex(parsed, table.name, 'x'));
		});
	}

	it('writes the layout build-minidex writes', () => {
		const output = serializeMinidex(parseMinidex(UPSTREAM_MAIN, MAIN.name), MAIN.name, 'https://play.pokemonshowdown.com/data/pokedex-mini.js');
		assert.match(output, /^\/\*\nDO NOT EDIT\n\nTHIS FILE IS AUTOGENERATED BY [^\n]*\n[^\n]*\n\*\/\n\nexports\.BattlePokemonSprites = \{\n/);
		assert.ok(output.includes('\n\tsubstitute:{exists:false,front:{w:34,h:39},back:{w:37,h:38}},\n'));
		assert.ok(output.includes('\n\trattata:{num:19,front:{w:43,h:61},frontf:{w:42,h:61},back:{w:43,h:64},backf:{w:54,h:69}},\n'));
		assert.ok(output.endsWith('\n\tpokestarufopropu2:{num:-5001}\n};\n'));
		const rows = output.split('exports.BattlePokemonSprites = {\n')[1].split('\n').slice(0, -2);
		for (const row of rows) assert.match(row, /^\t[a-z][a-z0-9]*:\{[a-z]+:(?:-?\d+|false|true|\{w:\d+,h:\d+\})(?:,[a-z]+:(?:-?\d+|\{w:\d+,h:\d+\}))*\},?$/);
	});

	const bulbasaur = '\tbulbasaur:{num:1,front:{w:45,h:49},back:{w:52,h:50}},';
	const withRow = row => UPSTREAM_MAIN.replace(bulbasaur, row);
	const rejected = {
		'a value that closes the object and runs code': withRow('\tbulbasaur:{num:1};alert(1);//,front:{w:45,h:49}},'),
		'a row that closes the table and runs code': withRow('\tbulbasaur:{num:1}};alert(1);exports.BattlePokemonSprites={x:{num:1},'),
		'a getter': withRow('\tbulbasaur:{get num() { return alert(1); }},'),
		'a getter named like a field': withRow('\tbulbasaur:{num:1,get front() { return alert(1); }},'),
		'a function value': withRow('\tbulbasaur:{num:function () { alert(1); }},'),
		'a method': withRow('\tbulbasaur:{num() { alert(1); }},'),
		'an arrow function': withRow('\tbulbasaur:() => alert(1),'),
		'a call in a value': withRow('\tbulbasaur:{num:(alert(1), 1)},'),
		'a computed key': withRow('\t[alert(1)]:{num:1},'),
		'a computed field': withRow('\tbulbasaur:{[alert(1)]:1},'),
		'a __proto__ key': withRow('\t__proto__:{num:1},'),
		'a constructor key': withRow('\tconstructor:{num:1},'),
		'a quoted key': withRow('\t"bulbasaur":{num:1},'),
		'a unicode-escaped key': withRow('\tbulb\\u0061saur:{num:1},'),
		'a spread': withRow('\t...globalThis,'),
		'a string value': withRow('\tbulbasaur:{num:"1"},'),
		'a template literal': withRow('\tbulbasaur:{num:`${alert(1)}`},'),
		'a hex number': withRow('\tbulbasaur:{num:0x1},'),
		'an exponent': withRow('\tbulbasaur:{num:1e3},'),
		'a fraction': withRow('\tbulbasaur:{num:1.5},'),
		'a BigInt': withRow('\tbulbasaur:{num:1n},'),
		'a zero size': withRow('\tbulbasaur:{num:1,front:{w:0,h:49}},'),
		'an unknown field': withRow('\tbulbasaur:{num:1,src:1},'),
		'an unknown size field': withRow('\tbulbasaur:{num:1,front:{w:45,h:49,y:3}},'),
		'a duplicate field': withRow('\tbulbasaur:{num:1,num:2},'),
		'a comment inside the table': withRow('\tbulbasaur:{num:1/* */},'),
		'an extra statement after the table': UPSTREAM_MAIN + 'alert(1);\n',
		'an extra statement before the table': UPSTREAM_MAIN.replace('exports.', 'alert(1);\nexports.'),
		'a second assignment': UPSTREAM_MAIN + UPSTREAM_MAIN,
		'a different global': UPSTREAM_MAIN.replace('exports.BattlePokemonSprites', 'exports.BattlePokemonSpritesBW'),
		'an assignment to window': UPSTREAM_MAIN.replace('exports.', 'window.'),
		'a bracketed global': UPSTREAM_MAIN.replace('exports.BattlePokemonSprites', 'exports["BattlePokemonSprites"]'),
		'a missing semicolon and a trailing call': UPSTREAM_MAIN.replace('};\n', '}\n(alert(1))\n'),
		'an HTML error page': '<!DOCTYPE html>\n<html><head><title>502 Bad Gateway</title></head><body><h1>502</h1></body></html>\n',
		'a truncated file': UPSTREAM_MAIN.slice(0, Math.floor(UPSTREAM_MAIN.length / 2)),
		'a file cut before the closing brace': UPSTREAM_MAIN.replace(/\n\};\n$/, '\n'),
		'an unterminated header comment': UPSTREAM_MAIN.replace('*/\n', ''),
		'an empty file': '',
	};
	for (const [label, text] of Object.entries(rejected)) {
		it(`rejects ${label}`, () => {
			assert.throws(() => parseMinidex(text, MAIN.name), /at line \d+/);
		});
	}

	it('rejects input that is not text', () => {
		assert.throws(() => parseMinidex(Buffer.from(UPSTREAM_MAIN), MAIN.name));
		assert.throws(() => parseMinidex(undefined, MAIN.name));
	});

	it('never evaluates what it reads', () => {
		const source = fs.readFileSync(scriptPath, 'utf8');
		assert.doesNotMatch(source, /\beval\b|\bFunction\s*\(|require\(['"](?:node:)?vm['"]\)|\bimport\(|runIn(?:New|This)?Context/);
	});
});

describe('upstream minidex refresh', () => {
	it('reads the resource server the build uses and only accepts a bare host', () => {
		assert.equal(resolveHost(tempRoot('Sprites.Example.test:8443')), 'sprites.example.test:8443');
		assert.equal(resolveHost(tempRoot()), 'play.pokemonshowdown.com');
		for (const bad of ['https://evil.test', 'evil.test/data', 'user@evil.test', 'evil.test\n', 'evil.test?', '', 7]) {
			assert.equal(resolveHost(tempRoot(bad)), 'play.pokemonshowdown.com', JSON.stringify(bad));
		}
	});

	it('refuses to fetch anything but https', async () => {
		let hits = 0;
		const server = http.createServer((req, res) => {
			hits++;
			res.end(fullSize(UPSTREAM_MAIN));
		});
		await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
		try {
			const url = `http://127.0.0.1:${server.address().port}/data/pokedex-mini.js`;
			await assert.rejects(fetchText(url), /non-https/);
			assert.equal(hits, 0);
		} finally {
			server.close();
		}
	});

	it('writes validated copies of both tables and a last good copy', async () => {
		const root = tempRoot('sprites.example.test');
		const { urls, fetchImpl } = serve({ [MAIN.file]: fullSize(UPSTREAM_MAIN), [BW.file]: fullSize(UPSTREAM_BW) });
		const { result, line } = await run(root, fetchImpl);
		assert.equal(result.status, 'fetched');
		assert.deepEqual(urls.sort(), [
			'https://sprites.example.test/data/pokedex-mini-bw.js',
			'https://sprites.example.test/data/pokedex-mini.js',
		]);
		assert.match(line, /DONE \(1024 \+ 1023 entries\)$/);
		for (const table of [MAIN, BW]) {
			const written = fs.readFileSync(outFile(root, table.file), 'utf8');
			assert.equal(fs.readFileSync(cacheFile(root, table.file), 'utf8'), written);
			assert.deepEqual(plain(evaluate(written)[table.name]), plain(evaluate(fullSize(table.text))[table.name]));
		}
		assert.deepEqual(fs.readdirSync(path.dirname(outFile(root, MAIN.file))).sort(), [BW.file, MAIN.file]);
	});

	it('restores the last good copy when the fetch fails', async () => {
		const root = tempRoot('sprites.example.test');
		await run(root, serve({ [MAIN.file]: fullSize(UPSTREAM_MAIN), [BW.file]: fullSize(UPSTREAM_BW) }).fetchImpl);
		const good = [MAIN, BW].map(table => fs.readFileSync(outFile(root, table.file), 'utf8'));
		for (const table of [MAIN, BW]) fs.unlinkSync(outFile(root, table.file));

		const offline = new TypeError('fetch failed', { cause: new Error('getaddrinfo ENOTFOUND sprites.example.test') });
		const { result, line } = await run(root, () => Promise.reject(offline));
		assert.equal(result.status, 'restored');
		assert.match(line, /FAILED \(fetch failed: getaddrinfo ENOTFOUND sprites\.example\.test\); restored the last good copy from caches\/phnn-minidex$/);
		assert.deepEqual([MAIN, BW].map(table => fs.readFileSync(outFile(root, table.file), 'utf8')), good);
	});

	it('keeps the pair together when only one table fails validation', async () => {
		const root = tempRoot('sprites.example.test');
		await run(root, serve({ [MAIN.file]: fullSize(UPSTREAM_MAIN), [BW.file]: fullSize(UPSTREAM_BW) }).fetchImpl);
		const good = [MAIN, BW].map(table => fs.readFileSync(outFile(root, table.file), 'utf8'));

		const fresh = serve({ [MAIN.file]: fullSize(UPSTREAM_MAIN, 1), [BW.file]: '<html><body>502 Bad Gateway</body></html>' });
		const { result, line } = await run(root, fresh.fetchImpl);
		assert.equal(result.status, 'restored');
		assert.match(line, /FAILED \(pokedex-mini-bw\.js: expected 'exports\.BattlePokemonSpritesBW =' at line 1\)/);
		assert.deepEqual([MAIN, BW].map(table => fs.readFileSync(outFile(root, table.file), 'utf8')), good);
	});

	it('rejects a well-formed table that is too small', async () => {
		const root = tempRoot('sprites.example.test');
		const { result, line } = await run(root, serve({ [MAIN.file]: UPSTREAM_MAIN, [BW.file]: fullSize(UPSTREAM_BW) }).fetchImpl);
		assert.equal(result.status, 'missing');
		assert.match(line, /FAILED \(pokedex-mini\.js has only 24 entries\); there is no last good copy in caches\/phnn-minidex yet, so battles show static sprites$/);
		assert.equal(fs.existsSync(outFile(root, MAIN.file)), false);
	});

	it('does not restore a tampered last good copy', async () => {
		const root = tempRoot('sprites.example.test');
		await run(root, serve({ [MAIN.file]: fullSize(UPSTREAM_MAIN), [BW.file]: fullSize(UPSTREAM_BW) }).fetchImpl);
		for (const table of [MAIN, BW]) fs.unlinkSync(outFile(root, table.file));
		fs.appendFileSync(cacheFile(root, MAIN.file), 'alert(1);\n');

		const { result, line } = await run(root, () => Promise.reject(new Error('offline')));
		assert.equal(result.status, 'missing');
		assert.match(line, /the last good copy is unusable \(pokedex-mini\.js: unexpected text after the table at line \d+\)/);
		for (const table of [MAIN, BW]) assert.equal(fs.existsSync(outFile(root, table.file)), false);
	});

	it('writes a restored copy from the parsed data, never the cached bytes', async () => {
		for (const sep of ['\r', '\u2028', '\u2029']) {
			const root = tempRoot('sprites.example.test');
			await run(root, serve({ [MAIN.file]: fullSize(UPSTREAM_MAIN), [BW.file]: fullSize(UPSTREAM_BW) }).fetchImpl);
			const good = [MAIN, BW].map(table => fs.readFileSync(outFile(root, table.file), 'utf8'));
			for (const table of [MAIN, BW]) fs.unlinkSync(outFile(root, table.file));
			const cached = fs.readFileSync(cacheFile(root, MAIN.file), 'utf8');
			fs.writeFileSync(cacheFile(root, MAIN.file), `// note${sep}globalThis.pwned = 1; //\n` + cached);

			const { result } = await run(root, () => Promise.reject(new Error('offline')));
			assert.equal(result.status, 'missing', JSON.stringify(sep));
			for (const table of [MAIN, BW]) assert.equal(fs.existsSync(outFile(root, table.file)), false);

			fs.writeFileSync(cacheFile(root, MAIN.file), '/* note */\n' + cached);
			assert.equal((await run(root, () => Promise.reject(new Error('offline')))).result.status, 'restored');
			assert.deepEqual([MAIN, BW].map(table => fs.readFileSync(outFile(root, table.file), 'utf8')), good);
		}
	});

	it('stops reading a response as soon as it passes the size cap', async () => {
		const realFetch = globalThis.fetch;
		let sent = 0;
		const chunk = new Uint8Array(64 * 1024).fill(0x20);
		globalThis.fetch = async () => new Response(new ReadableStream({
			pull(controller) {
				sent += chunk.byteLength;
				controller.enqueue(chunk);
			},
		}), { status: 200 });
		try {
			await assert.rejects(fetchText('https://sprites.example.test/data/pokedex-mini.js'), /is too large/);
		} finally {
			globalThis.fetch = realFetch;
		}
		assert.ok(sent < 5 * 1024 * 1024, `read ${sent} bytes`);
	});

	it('never throws, even with no last good copy and an odd failure', async () => {
		const root = tempRoot();
		const { result, line } = await run(root, () => {
			throw 'socket hang up';
		});
		assert.equal(result.status, 'missing');
		assert.match(line, /^Using upstream's animated sprite dimensions from https:\/\/play\.pokemonshowdown\.com\/data\/\.\.\. FAILED \(socket hang up\); there is no last good copy in caches\/phnn-minidex yet/);
		assert.equal(fs.existsSync(outFile(root, MAIN.file)), false);
	});

	it('runs from build-minidex when it skips, into ignored paths', () => {
		const buildMinidex = fs.readFileSync(path.join(repoRoot, 'build-tools/build-minidex'), 'utf8');
		assert.match(buildMinidex, /console\.log\('SKIPPED'\);\n\tawait \(await import\('\.\/phnn-minidex\.js'\)\)\.default\.updateMinidex\(\);\n\}/);
		const gitignore = fs.readFileSync(path.join(repoRoot, '.gitignore'), 'utf8').split('\n');
		assert.ok(gitignore.includes('/play.pokemonshowdown.com/data/'));
		assert.ok(gitignore.includes('/caches/'));
	});
});
